### Arrays

- Estructuras de datos secuencia, donde los elementos estan almacenados en posiciones de memoria continuas      

- Es una estructura de datos muy similar a las listas, pero solo puede almacenar el mismo tipo de datos     

- La libreria array permite crear estas estructuas de datos, que almacenan datos de tipo entero, decimal, entre otros       

#### Arrays de Arrays

- La libreria numPy permite crear estas estructuras de datos, que almacenan datos de tipo entero, decimal, entre otros      

- La libreria numPy no esta predeterminada en Python, por lo cual, necesita ser instalada para su uso.      

##### CREAR VECTOR

In [1]:
import numpy as np

vector = np.array([1,2,3,4,5])
print(vector)

[1 2 3 4 5]


#### CREAR MATRICES

##### Array()

In [ ]:
matriz = np.array([(1,2,3), (3,4,5)])
print(matriz)

for fila in matriz:
    print(fila)


| Concepto     | Qué hace                                     | Sintaxis general                             | Ejemplo / Salida          |
|-------------|----------|----------|--------|
| array        | Crea un arreglo homogéneo del módulo array   | array.array(tipo_dato, [elementos])          | array('i', [1, 2, 3]) → array('i', [1,2,3])  |
| numpy.array  | Crea un array de NumPy (ndarray)             | np.array([elementos])                        | np.array([1,2,3]) → [1 2 3]                  |
| numpy.empty  | Crea un array sin inicializar valores         | np.empty(formato, dtype=float)               | np.empty(3) → [x.xe-311 ...]                 |
| numpy.zeros  | Crea un array lleno de ceros                 | np.zeros(formato, dtype=float)               | np.zeros((2,2)) → [[0. 0.] [0. 0.]]          |
| numpy.ones   | Crea un array lleno de unos                  | np.ones(formato, dtype=float)                | np.ones((2,2)) → [[1. 1.] [1. 1.]]           |



#### Empty()

In [3]:


matriz_aleatoria = np.empty([2,2])
print(matriz_aleatoria)

[[1.06225067e-311 1.06135860e-311]
 [6.95271371e-310 0.00000000e+000]]


In [ ]:
matriz_aleatoria = np.empty([2,2], dtype = int)     # → si no especificamos nos toma como que es un tipo de dato decimal por default 
print(matriz_aleatoria)

[[  2150019301432   2148213730050]
 [140724492064216               0]]


In [5]:
vectoraleatorio = np.empty(5)
print(vectoraleatorio)

[3.47739925e-81 1.13897400e-42 2.00546596e-52 2.33859743e-52
 4.66301032e-33]


##### Zeros()

In [6]:
matriceszeros = np.zeros([2,3], dtype=int)
print(matriceszeros)

[[0 0 0]
 [0 0 0]]


##### Ones()

In [7]:
vectorunos = np.ones(4)
print(vectorunos)

[1. 1. 1. 1.]


##### Arange()

- Que hace -> crea un array NumPy con valores en unrango numerico, equiespaciados (es decir, separados por un paso constante)

- Funciona parecido a la funcion range() pero devuelve un array de NumPy no una lista

- Sintaxis:     

        numpy.arrange(inicio, fin, paso, dtype = None)

    inicio → valor inicial del rango (por defecto 0)        
    fin → valor hasta el cual genera (NO se incluye el final)           
    paso → diferencia entre cada numero (por defecto 1 )         
    dtype → tipo de dato opcional (opcional, ej : int, float)           

In [9]:
matriz1 =  np.arange(0,4,2)
print(matriz1)


[0 2]


#### Reshape()

- Permite que el vector que tenemos armado se organice de una forma diferente y lo queremos devolver como una matriz
- Dimensiones


In [12]:
matriz1 = np.arange(4)
print(matriz1)

[0 1 2 3]


In [10]:
matriz1 = np.arange(4).reshape(2,2)
print(matriz1)

[[0 1]
 [2 3]]


##### Sort()

- Organiza sobre el mismo dato 

In [13]:
matriz1 = np.arange(0,4)
print(matriz1)
matriz1.sort()
print(matriz1)

[0 1 2 3]
[0 1 2 3]


In [ ]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

sorted_array = np.sort(a)     # -> ordenamos la matriz -> la ordena por fila o sea por []
print('The sorted array is: ')
print(sorted_array)

The sorted array is: 
[[ 5 11 12]
 [ 6 10 15]
 [ 8 10 12]
 [ 8 12 15]
 [34 78 90]]


-> Por defecto -> organiza por filas 

-> Ahora lo que queremos es organizar por axis         

        - Axis -> trabaja sobre las columnas 


In [ ]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

sorted_array = np.sort(a, axis = 0)     # -> ordenamos la matriz -> la ordena por columna
print('The sorted array is: ')
print(sorted_array)

The sorted array is: 
[[10  6  5]
 [11  8  8]
 [12 12 10]
 [15 15 12]
 [34 78 90]]


        Que pasa si escribimos la axis como None?
- Toda la matriz la convierte en un array (vector) y la organiza 


In [18]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

sorted_array = np.sort(a, axis = None)    
print('The sorted array is: ')
print(sorted_array)
print(type(sorted_array))

The sorted array is: 
[ 5  6  8  8 10 10 11 12 12 12 15 15 34 78 90]
<class 'numpy.ndarray'>


##### Sum()

- Conocer todos los elementos de una matriz
- Es un vector de vectores 

In [19]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

print(a.sum())

326


##### Max()

- Obtiene el maximo elemento de una MATRIZ 

In [ ]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

print(a.max())

##### Min()

- Obtiene el minimo elemento de una MATRIZ 

In [20]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

print(a.min())

5


        SUMA DE LAS COLUMNAS DE UNA MATRIZ

In [21]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

print(a.sum(axis = 0))

[ 82 119 125]


        SUMA DE LAS FILAS DE UNA MATRIZ 

In [22]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

sum_filas = a.sum(axis = 1)
print(sum_filas)
print(type(sum_filas))

[ 28  31  30  35 202]
<class 'numpy.ndarray'>


        MAXIMO ELEMENTO DE CADA COLUMNA 

In [23]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

max_elem_col = a.max(axis = 0)
print(max_elem_col)

[34 78 90]


        MINIMO ELEMENTO DE CADA COLUMNA 

In [ ]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])

min_elem_col = a.min(axis = 0)
print(min_elem_col)

[10  6  5]


##### Dimension de una matriz 

- No es un metodo -> no necesita llamado 

In [26]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])
print(a.ndim)

2


##### Forma de una matriz 

- Nos devuelve la cantidad de filas y columnas 

In [27]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])
print(a.shape)

(5, 3)


##### Tamano

- Nos devuelve la cantidad de elementos de una matriz

In [28]:
a = np.array([[11,12,5], [15,6,10], [10,8,12], [12,15,8], [34,78,90]])
print(a.size)


15
