## Creacion de arrays - Fundamentos

In [ ]:

# Celda de imports
import numpy as np

print("NumPy version:", np.__version__)

In [ ]:

# Arrays básicos
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("Array 1D:", arr_1d)
print("Array 2D:\n", arr_2d)
print("Array 3D shape:", arr_3d.shape)

# Funciones de creación útiles
zeros = np.zeros((3, 4))
ones = np.ones((2, 3))
identity = np.eye(3)
random_vals = np.random.random((2, 3))

print("\nZeros 3x4:\n", zeros)
print("\nIdentidad 3x3:\n", identity)

# Rangos y secuencias
range_arr = np.arange(0, 10, 2)  # inicio, fin, paso
linspace_arr = np.linspace(0, 1, 5)  # inicio, fin, cantidad

print("\nArange:", range_arr)
print("Linspace:", linspace_arr)

## Propiedades de los arrays

In [2]:
import numpy as np
import random 

data = np.random.randint(0, 100, (4, 5))
print("Array ejemplo:\n", data)
print(f"Shape: {data.shape}")
print(f"Dimensiones: {data.ndim}")
print(f"Tamaño total: {data.size}")
print(f"Tipo de datos: {data.dtype}")
print(f"Bytes por elemento: {data.itemsize}")

Array ejemplo:
 [[ 6 12  0 76 63]
 [ 6 96 37 31 17]
 [ 8 46 53 19 26]
 [46 25 25 61 45]]
Shape: (4, 5)
Dimensiones: 2
Tamaño total: 20
Tipo de datos: int64
Bytes por elemento: 8


## Matrices triangulares

#### Contenido
- np.tril: parte triangular inferior como matriz
- np.tril_indices: indices (coordenadas) de la parte inferior
- np.triu: parte triangular superior como matriz

np.tril(matriz, k=0)

devuelve una matriz donde se conservan los elementos de la
parte triangular inferior y se reemplaza con 0 todo lo que queda por 
encima de la diagonal elegida


In [ ]:

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Matriz A:\n", A)
print("\nnp.tril(A, 0):\n", np.tril(A, 0))   # incluye diagonal
print("\nnp.tril(A, -1):\n", np.tril(A, -1)) # debajo de la diagonal (sin diagonal)
print("\nnp.tril(A, 1):\n", np.tril(A, 1))   # incluye una diagonal por encima


Matriz A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

np.tril(A, 0):
 [[1 0 0]
 [4 5 0]
 [7 8 9]]

np.tril(A, -1):
 [[0 0 0]
 [4 0 0]
 [7 8 0]]

np.tril(A, 1):
 [[1 2 0]
 [4 5 6]
 [7 8 9]]


np.tril_indices(n, k=0)

devuelve las coordenadas (dos arrays: filas y columnas)
de los elementos que pertenecen a la parte triangular inferior 
de una matriz nxn

In [ ]:


n = 3 # (valor de la matriz nxn)
filas, cols = np.tril_indices(n, k=-1)  # solo debajo de la diagonal
print("filas:", filas)
print("cols :", cols)

print("\nElementos A[filas, cols]:", A[filas, cols])  # valores debajo de la diagonal de A


filas: [1 2 2]
cols : [0 0 1]

Elementos A[filas, cols]: [4 7 8]


NumPy toma estos arrays y accede a las posiciones de A en pares:

- A[1,0] (fila 1, columna 0) → elemento 4     
- A[2,0] (fila 2, columna 0) → elemento 7     
- A[2,1] (fila 2, columna 1) → elemento 8     

In [ ]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
     
# Las posiciones accedidas son:
#     col 0   col 1   col 2
#    ┌───────┬───────┬───────┐
#    │       │       │       │
# f0 │   1   │   2   │   3   │
#    │       │       │       │
#    ├───────┼───────┼───────┤
#    │   ↓   │       │       │
# f1 │   4   │   5   │   6   │
#    │       │       │       │
#    ├───────┼───────┼───────┤
#    │   ↓   │   ↓   │       │
# f2 │   7   │   8   │   9   │
#    │       │       │       │
#    └───────┴───────┴───────┘

# A[filas, cols] devuelve: [4, 7, 8]

np.triu(matriz, k=0)

Análogo de `np.tril` pero para la **parte triangular superior**.



In [13]:
print("np.triu(A, 0):\n", np.triu(A, 0))
print("\nnp.triu(A, 1):\n", np.triu(A, 1))   # estrictamente arriba (sin diagonal)
print("\nnp.triu(A, -1):\n", np.triu(A, -1)) # incluye una diagonal por debajo


np.triu(A, 0):
 [[1 2 3]
 [0 5 6]
 [0 0 9]]

np.triu(A, 1):
 [[0 2 3]
 [0 0 6]
 [0 0 0]]

np.triu(A, -1):
 [[1 2 3]
 [4 5 6]
 [0 8 9]]


## Checks vectorizados (sin `for`)

**Triangular superior:** todos los elementos *debajo* de la diagonal deben ser 0.
- Opción con máscara por índices:
```python
li = np.tril_indices(n, k=-1)
np.all(A[li] == 0)
```
- Opción con matriz triangular:
```python
np.all(np.tril(A, -1) == 0)
```

**Triangular inferior:** todos los elementos *encima* de la diagonal deben ser 0.
- Índices:
```python
ui = np.triu_indices(n, k=1)
np.all(A[ui] == 0)
```
- Matriz triangular:
```python
np.all(np.triu(A, 1) == 0)
```


In [14]:
def es_cuadrada(M):
    return (M.ndim == 2) and (M.shape[0] == M.shape[1])

def es_triangular_superior(M):
    if not es_cuadrada(M):
        return False
    n = M.shape[0]
    li = np.tril_indices(n, k=-1)  # posiciones debajo de la diagonal
    return np.all(M[li] == 0)

def es_triangular_inferior(M):
    if not es_cuadrada(M):
        return False
    n = M.shape[0]
    ui = np.triu_indices(n, k=1)   # posiciones encima de la diagonal
    return np.all(M[ui] == 0)

# Pruebas rápidas
Tsup = np.array([[1,2,3],
                 [0,5,6],
                 [0,0,9]])

Tinf = np.array([[1,0,0],
                 [4,5,0],
                 [7,8,9]])

NoTri = np.array([[1,2,3],
                  [4,5,6],
                  [0,0,9]])

print("es_triangular_superior(Tsup) →", es_triangular_superior(Tsup))
print("es_triangular_inferior(Tsup) →", es_triangular_inferior(Tsup))

print("es_triangular_superior(Tinf) →", es_triangular_superior(Tinf))
print("es_triangular_inferior(Tinf) →", es_triangular_inferior(Tinf))

print("es_triangular_superior(NoTri) →", es_triangular_superior(NoTri))
print("es_triangular_inferior(NoTri) →", es_triangular_inferior(NoTri))


es_triangular_superior(Tsup) → True
es_triangular_inferior(Tsup) → False
es_triangular_superior(Tinf) → False
es_triangular_inferior(Tinf) → True
es_triangular_superior(NoTri) → False
es_triangular_inferior(NoTri) → False


## Indexado y slice

In [3]:

arr = np.array([[0, 1, 2, 3, 4],
               [5, 6, 7, 8, 9],
               [10, 11, 12, 13, 14],
               [15, 16, 17, 18, 19]])
print("Array base:\n", arr)

# Indexing básico
print("\nElemento [1,2]:", arr[1, 2])
print("Primera fila:", arr[0, :])
print("Segunda columna:", arr[:, 1])

# Slicing avanzado
print("\nPrimeras 2 filas, columnas 1-3:\n", arr[:2, 1:4])
print("Cada segunda fila:\n", arr[::2, :])

# Boolean indexing
mask = arr > 10
print("\nElementos > 10:", arr[mask])

# Fancy indexing
indices = [0, 2, 3]
print("Filas seleccionadas [0,2,3]:\n", arr[indices, :])

Array base:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

Elemento [1,2]: 7
Primera fila: [0 1 2 3 4]
Segunda columna: [ 1  6 11 16]

Primeras 2 filas, columnas 1-3:
 [[1 2 3]
 [6 7 8]]
Cada segunda fila:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]]

Elementos > 10: [11 12 13 14 15 16 17 18 19]
Filas seleccionadas [0,2,3]:
 [[ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]]


## Reshape y manipulacion de forma 

In [4]:

original = np.arange(12) # vector del 0 al 11
print("Original:", original)

# Reshape
reshaped = original.reshape(3, 4)
print("Reshape 3x4 del vector original:\n", reshaped)

# Flatten
flattened = reshaped.flatten()
print("Flatten de la matriz reshaped:", flattened)

# Transpose
transposed = reshaped.T
print("Matriz transpuesta:\n", transposed)

# Concatenación
arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6],
                 [7, 8]])

concat_v = np.vstack([arr1, arr2])  # vertical
concat_h = np.hstack([arr1, arr2])  # horizontal

print("\nConcatenación vertical:\n", concat_v)
print("Concatenación horizontal:\n", concat_h)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshape 3x4 del vector original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flatten de la matriz reshaped: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Matriz transpuesta:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Concatenación vertical:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenación horizontal:
 [[1 2 5 6]
 [3 4 7 8]]


## Broadcasting

In [5]:
# Broadcasting básico
arr = np.array([[1, 2, 3], [4, 5, 6]])
k = 10

print("Array original:\n", arr)
print("\nArray + 10:\n", arr + k)

# Broadcasting con arrays
row_vector = np.array([1, 2, 3])
col_vector = np.array([[10],
                       [20]])

print("\nRow vector:", row_vector)
print("Col vector:\n", col_vector)
print("Broadcasting sum:\n", row_vector + col_vector)

Array original:
 [[1 2 3]
 [4 5 6]]

Array + 10:
 [[11 12 13]
 [14 15 16]]

Row vector: [1 2 3]
Col vector:
 [[10]
 [20]]
Broadcasting sum:
 [[11 12 13]
 [21 22 23]]


## Operaciones aritméticas

In [7]:

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a =", a)
print("b =", b)

# Operaciones elemento a elemento
print("\nSuma:", a + b)
print("Multiplicación:", a * b)
print("Potencia:", a**2)

# Operaciones matriciales
matrix_a = np.array([[1, 2],
                     [3, 4]])
matrix_b = np.array([[5, 6],
                     [7, 8]])

print("\nMatriz A:\n", matrix_a)
print("Matriz B:\n", matrix_b)
print("Producto matricial A @ B:\n", matrix_a @ matrix_b)

# Funciones
x = np.linspace(0, 2 * np.pi, 17) # vector linealmente espaciado entre 0 y 2pi, 9 elementos
print("\nSeno de x:", np.sin(x))
print("\nSeno de x:", np.round(np.sin(x), 2))
print("\nExponencial:", np.exp([1, 2, 3]))

a = [1 2 3 4]
b = [5 6 7 8]

Suma: [ 6  8 10 12]
Multiplicación: [ 5 12 21 32]
Potencia: [ 1  4  9 16]

Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]
Producto matricial A @ B:
 [[19 22]
 [43 50]]

Seno de x: [ 0.00000000e+00  3.82683432e-01  7.07106781e-01  9.23879533e-01
  1.00000000e+00  9.23879533e-01  7.07106781e-01  3.82683432e-01
  1.22464680e-16 -3.82683432e-01 -7.07106781e-01 -9.23879533e-01
 -1.00000000e+00 -9.23879533e-01 -7.07106781e-01 -3.82683432e-01
 -2.44929360e-16]

Seno de x: [ 0.    0.38  0.71  0.92  1.    0.92  0.71  0.38  0.   -0.38 -0.71 -0.92
 -1.   -0.92 -0.71 -0.38 -0.  ]

Exponencial: [ 2.71828183  7.3890561  20.08553692]


## + Operaciones con matrices e inversa de una matriz

In [ ]:
A = np.array([[2,1],[5,3]])

A_inv = np.linalg.inv(A)   
print('Inversa de una matriz\n',A_inv)

detA= np.linalg.det(A)
print('Determinante de una matriz\n',A_inv)

A_inv_int = A_inv.astype(int)
print('Convertir a enteros (solo si son valores exactos)',A_inv_int)



## Operaciones estadísticas

In [6]:
data = np.random.normal(50, 15, 100)  # media=50, std=15, 100 elementos

print(f"Media: {np.mean(data):.2f}")
print(f"Mediana: {np.median(data):.2f}")
print(f"Desviación estándar: {np.std(data):.2f}")
print(f"Mínimo: {np.min(data):.2f}")
print(f"Máximo: {np.max(data):.2f}")

# Agregaciones por eje
matrix = np.random.randint(1, 10, (3, 4)) # random entre 1 y 10, tamaño 3x4
print("\nMatriz:\n", matrix)
print("Suma por filas (axis=1):", np.sum(matrix, axis=1))
print("Media por columnas (axis=0):", np.mean(matrix, axis=0))

Media: 49.18
Mediana: 47.26
Desviación estándar: 16.87
Mínimo: 13.45
Máximo: 90.60

Matriz:
 [[3 1 8 6]
 [8 5 7 8]
 [3 8 2 4]]
Suma por filas (axis=1): [18 28 17]
Media por columnas (axis=0): [4.66666667 4.66666667 5.66666667 6.        ]



## Sistemas de ecuaciones lineales

In [8]:
# Sistema de ecuaciones lineal => ecuación matricial AX = B

# Por ejemplo:
# 3x + 2y + z = 1
# 5x + 3y + 4z = 2
# x + y - z = 1

A = np.array([[3, 2, 1],
              [5, 3, 4],
              [1, 1, -1]])
B = np.array([1,
              2,
              1])

X = np.linalg.solve(A, B)
print("Solución >", X)

Solución > [-4.  6.  1.]


## Comparación de performance

In [9]:
# Comparación de performance
import time

# Lista de Python vs NumPy array
python_list = list(range(1000000))
numpy_array = np.arange(1000000)

# Suma con listas
start = time.time()
sum_list = sum(python_list)
time_list = time.time() - start

# Suma con NumPy
start = time.time()
sum_numpy = np.sum(numpy_array)
time_numpy = time.time() - start

print(f"Suma con listas Python: {time_list:.4f} segundos")
print(f"Suma con NumPy: {time_numpy:.4f} segundos")
print(f"NumPy es {time_list/time_numpy:.1f}x más rápido")

# Copia vs vista
original = np.arange(10)
view = original[::2]  # vista
copy = original[::2].copy()  # copia

print("\nOriginal:", original)
original[0] = 999
print("Después de modificar original[0]:")
print("Vista:", view)  # cambia porque es vista
print("Copia:", copy)  # no cambia porque es copia independiente

Suma con listas Python: 0.0100 segundos
Suma con NumPy: 0.0005 segundos
NumPy es 18.3x más rápido

Original: [0 1 2 3 4 5 6 7 8 9]
Después de modificar original[0]:
Vista: [999   2   4   6   8]
Copia: [0 2 4 6 8]
